orbs:
  docker: circleci/docker@1.5.0
  version: 2.1
jobs:
  build_test:
    docker:
       - image: circleci/node:12
    steps:
       - checkout
       - run:
           name: Install npm dependencies
           command:
            npm install --save
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup-remote_docker:  
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
          echo "$DOCKER_PWD" | docker login -u gopuc365 --password-stdin
          docker build -t gopuc365/nodejswebapp1:latest .
          docker push gopuc365/nodejswebapp1:latest
workflows:
  version: 2
  build_test:
    jobs:
      - build_test
      - build_docker_image
