version: 2.1
jobs:
  build_test:
    docker:
       - image: circleci/node:12
    steps:
       - checkout
       - run:
           name: Install npm dependencies
           command:
            npm install --save
  build_docker_image:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup-remote_docker:  
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
          # export TAG=0.2. << pipeline.number >>
          # export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME
          docker build -t nodejswebapp1 -t gopuc365/nodejswebapp1:latest .
          echo $DOCKER_PWD | docker login -u gopuc365 --password-stdin
          docker push gopuc365/nodejswebapp1:latest     
workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image
      
